STR R0 #1 ;STORE 1 IN REGISTER 0
STR R1 #5 ;STORE 5 IN REGISTER 1
ADD R2 R0 R1 ;ADD THE VALUES IN REGISTER 0 AND 1 TOGETHER AND STORE IN REGISTER 2
MUL R2 R2 #2 ;DOUBLE THE VALUE IN REGISTER 2
OUT R2 ;OUTPUT THE VALUE IN REGISTER 2